.TH "create_dict.py" 3 "Mon Sep 25 2017" "Version 1" "MyProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
create_dict.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBcreate_dict\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBcreate_dict\&.delimiters\fP = '\\'\\'/<?>,\&.:*\-+\\\\=`~!@#^&()_ ;{}[]|'"
.br
.ti -1c
.RI "\fBcreate_dict\&.folder_path\fP = raw_input('Please input the path to the folder\\t')"
.br
.ti -1c
.RI "dictionary \fBcreate_dict\&.document_dictionary\fP = {}"
.br
.ti -1c
.RI "\fBcreate_dict\&.document_word_count\fP"
.br
.ti -1c
.RI "\fBcreate_dict\&.dict_file\fP = open('dict\&.txt','w')"
.br
.ti -1c
.RI "\fBcreate_dict\&.key\fP"
.br
.ti -1c
.RI "\fBcreate_dict\&.end\fP"
.br
.ti -1c
.RI "\fBcreate_dict\&.file\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MyProject from the source code\&.
