.TH "create_dict" 3 "Mon Sep 25 2017" "Version 1" "MyProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
create_dict \- 
.SH SYNOPSIS
.br
.PP
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBdelimiters\fP = '\\'\\'/<?>,\&.:*\-+\\\\=`~!@#^&()_ ;{}[]|'"
.br
.ti -1c
.RI "\fBfolder_path\fP = raw_input('Please input the path to the folder\\t')"
.br
.ti -1c
.RI "dictionary \fBdocument_dictionary\fP = {}"
.br
.ti -1c
.RI "\fBdocument_word_count\fP"
.br
.ti -1c
.RI "\fBdict_file\fP = open('dict\&.txt','w')"
.br
.ti -1c
.RI "\fBkey\fP"
.br
.ti -1c
.RI "\fBend\fP"
.br
.ti -1c
.RI "\fBfile\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "string create_dict\&.delimiters = '\\'\\'/<?>,\&.:*\-+\\\\=`~!@#^&()_ ;{}[]|'"

.PP
Definition at line 18 of file create_dict\&.py\&.
.SS "create_dict\&.dict_file = open('dict\&.txt','w')"

.PP
Definition at line 33 of file create_dict\&.py\&.
.SS "dictionary create_dict\&.document_dictionary = {}"

.PP
Definition at line 25 of file create_dict\&.py\&.
.SS "create_dict\&.document_word_count"

.PP
Definition at line 30 of file create_dict\&.py\&.
.SS "create_dict\&.end"

.PP
Definition at line 35 of file create_dict\&.py\&.
.SS "create_dict\&.file"

.PP
Definition at line 35 of file create_dict\&.py\&.
.SS "create_dict\&.folder_path = raw_input('Please input the path to the folder\\t')"

.PP
Definition at line 24 of file create_dict\&.py\&.
.SS "create_dict\&.key"

.PP
Definition at line 35 of file create_dict\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MyProject from the source code\&.
