.TH "dict_functions.py" 3 "Mon Sep 25 2017" "Version 1" "MyProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dict_functions.py \- 
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBdict_functions\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBdict_functions\&.remove_delimiters\fP (text_line)"
.br
.ti -1c
.RI "def \fBdict_functions\&.format_text\fP (text_line)"
.br
.ti -1c
.RI "def \fBdict_functions\&.create_dictionary\fP (file_path, document_word_count)"
.br
.ti -1c
.RI "def \fBdict_functions\&.text_formatting\fP (my_dictionary)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBdict_functions\&.delimiters\fP = '\\'\\'/<?>,\&.:*\-+\\\\=`~!@#^&()_ ;{}[]|'"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for MyProject from the source code\&.
