.TH "diff" 3 "Mon Sep 25 2017" "Version 1" "MyProject" \" -*- nroff -*-
.ad l
.nh
.SH NAME
diff \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBinner_product\fP (\fBdocument_one_dictionary\fP, \fBdocument_two_dictionary\fP)"
.br
.ti -1c
.RI "def \fBcalculate_distance\fP (\fBdocument_one_dictionary\fP, \fBdocument_two_dictionary\fP)"
.br
.ti -1c
.RI "def \fBensure_dir\fP (file_path)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "string \fBdelimiters\fP = '\\'\\'/<?>,\&.:*\-+\\\\=`~!@#^&()_ ;{}[]|'"
.br
.ti -1c
.RI "dictionary \fBdocument_word_count\fP = {}"
.br
.ti -1c
.RI "\fBstart\fP = time\&.clock()"
.br
.ti -1c
.RI "\fBfolder_path\fP = raw_input('Please input the path to the folder\\t')"
.br
.ti -1c
.RI "dictionary \fBdocument_dictionary\fP = {}"
.br
.ti -1c
.RI "\fBoutput_folder_path\fP = raw_input('Please input the path to the output folder\\t')"
.br
.ti -1c
.RI "dictionary \fBresult_dictionary\fP = {}"
.br
.ti -1c
.RI "dictionary \fBtemp\fP = {}"
.br
.ti -1c
.RI "\fBdict_file\fP = open('dict\&.txt','r')"
.br
.ti -1c
.RI "\fBtext_line\fP = text_line\&.rstrip()"
.br
.ti -1c
.RI "\fBtext_line_divided\fP = text_line\&.split(' ')"
.br
.ti -1c
.RI "dictionary \fBtemp_dictionary\fP = {}"
.br
.ti -1c
.RI "\fBidf_key\fP = math\&.log(len(\fBdocument_dictionary\fP) / (\fBdocument_word_count\fP[key] * 1\&.0))"
.br
.ti -1c
.RI "\fBtf_key\fP = \fBdocument_dictionary\fP[filename][key]"
.br
.ti -1c
.RI "\fBfile_index\fP = os\&.listdir(\fBfolder_path\fP)"
.br
.ti -1c
.RI "\fBfile_index_one\fP = \fBfile_index\fP[index_one]"
.br
.ti -1c
.RI "\fBfile_index_two\fP = \fBfile_index\fP[index_two]"
.br
.ti -1c
.RI "\fBdocument_one_dictionary\fP = \fBdocument_dictionary\fP[\fBfile_index_one\fP]"
.br
.ti -1c
.RI "\fBdocument_two_dictionary\fP = \fBdocument_dictionary\fP[\fBfile_index_two\fP]"
.br
.ti -1c
.RI "\fBresult\fP = \fBcalculate_distance\fP(\fBdocument_one_dictionary\fP, \fBdocument_two_dictionary\fP)"
.br
.ti -1c
.RI "\fBend\fP"
.br
.ti -1c
.RI "\fBsorted_result\fP = sorted(result_dictionary\&.items(), key=operator\&.itemgetter(1))"
.br
.ti -1c
.RI "\fBresult_file_name\fP = raw_input('Please enter the name of \fBfile\fP where you wish to save the result\&.\\t')"
.br
.ti -1c
.RI "\fBresult_file\fP = open(\fBresult_file_name\fP ,'w')"
.br
.ti -1c
.RI "\fBfile\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "def diff\&.calculate_distance ( document_one_dictionary,  document_two_dictionary)"

.PP
.nf
Function name : inner_product
Input arguments :
    1. dictionary document_one_dictionary: The dictionary corresponding to document one.
    2. dictionary document_two_dictionary: The dictionary corresponding to document two.
Purpose : To find the distance between two documents
Return Value : The cosine distance of two vectors 

.fi
.PP
 
.PP
Definition at line 42 of file diff\&.py\&.
.SS "def diff\&.ensure_dir ( file_path)"

.PP
.nf
Function name : inner_product
Input arguments :
    1. string file_path : The path of the folder.
Purpose : To create a directory if it does not exists.
.fi
.PP
 
.PP
Definition at line 58 of file diff\&.py\&.
.SS "def diff\&.inner_product ( document_one_dictionary,  document_two_dictionary)"

.PP
.nf
Function name : inner_product
Input arguments :
    1. dictionary document_one_dictionary : The dictionary corresponding to document one.
    2. dictionary document_two_dictionary : The dictionary corresponding to document two.
Purpose : To find the inner product of two vectors
Return Value : The inner product of two vectors 

.fi
.PP
 
.PP
Definition at line 26 of file diff\&.py\&.
.SH "Variable Documentation"
.PP 
.SS "string diff\&.delimiters = '\\'\\'/<?>,\&.:*\-+\\\\=`~!@#^&()_ ;{}[]|'"

.PP
Definition at line 18 of file diff\&.py\&.
.SS "diff\&.dict_file = open('dict\&.txt','r')"

.PP
Definition at line 83 of file diff\&.py\&.
.SS "dictionary diff\&.document_dictionary = {}"

.PP
Definition at line 72 of file diff\&.py\&.
.SS "diff\&.document_one_dictionary = \fBdocument_dictionary\fP[\fBfile_index_one\fP]"

.PP
Definition at line 111 of file diff\&.py\&.
.SS "diff\&.document_two_dictionary = \fBdocument_dictionary\fP[\fBfile_index_two\fP]"

.PP
Definition at line 113 of file diff\&.py\&.
.SS "dictionary diff\&.document_word_count = {}"

.PP
Definition at line 22 of file diff\&.py\&.
.SS "diff\&.end"

.PP
Definition at line 117 of file diff\&.py\&.
.SS "diff\&.file"

.PP
Definition at line 130 of file diff\&.py\&.
.SS "diff\&.file_index = os\&.listdir(\fBfolder_path\fP)"

.PP
Definition at line 103 of file diff\&.py\&.
.SS "diff\&.file_index_one = \fBfile_index\fP[index_one]"

.PP
Definition at line 108 of file diff\&.py\&.
.SS "diff\&.file_index_two = \fBfile_index\fP[index_two]"

.PP
Definition at line 109 of file diff\&.py\&.
.SS "diff\&.folder_path = raw_input('Please input the path to the folder\\t')"

.PP
Definition at line 71 of file diff\&.py\&.
.SS "diff\&.idf_key = math\&.log(len(\fBdocument_dictionary\fP) / (\fBdocument_word_count\fP[key] * 1\&.0))"

.PP
Definition at line 96 of file diff\&.py\&.
.SS "diff\&.output_folder_path = raw_input('Please input the path to the output folder\\t')"

.PP
Definition at line 73 of file diff\&.py\&.
.SS "diff\&.result = \fBcalculate_distance\fP(\fBdocument_one_dictionary\fP, \fBdocument_two_dictionary\fP)"

.PP
Definition at line 115 of file diff\&.py\&.
.SS "dictionary diff\&.result_dictionary = {}"

.PP
Definition at line 77 of file diff\&.py\&.
.SS "diff\&.result_file = open(\fBresult_file_name\fP ,'w')"

.PP
Definition at line 128 of file diff\&.py\&.
.SS "diff\&.result_file_name = raw_input('Please enter the name of \fBfile\fP where you wish to save the result\&.\\t')"

.PP
Definition at line 127 of file diff\&.py\&.
.SS "diff\&.sorted_result = sorted(result_dictionary\&.items(), key=operator\&.itemgetter(1))"

.PP
Definition at line 123 of file diff\&.py\&.
.SS "diff\&.start = time\&.clock()"

.PP
Definition at line 69 of file diff\&.py\&.
.SS "diff\&.temp = {}"

.PP
Definition at line 78 of file diff\&.py\&.
.SS "dictionary diff\&.temp_dictionary = {}"

.PP
Definition at line 92 of file diff\&.py\&.
.SS "diff\&.text_line = text_line\&.rstrip()"

.PP
Definition at line 85 of file diff\&.py\&.
.SS "diff\&.text_line_divided = text_line\&.split(' ')"

.PP
Definition at line 86 of file diff\&.py\&.
.SS "diff\&.tf_key = \fBdocument_dictionary\fP[filename][key]"

.PP
Definition at line 97 of file diff\&.py\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for MyProject from the source code\&.
